// AUTO-GENERATED by scripts/export-seeds.ts — do not edit by hand
// last_fetched_at is intentionally excluded — it is runtime state, not configuration.
// Settings here propagate to any machine that runs this seed after a git pull.
import Database from "better-sqlite3";
import path from "path";

const db = new Database(path.join(process.cwd(), "db", "command-center.db"));

const settings: Array<{ key: string; value: string }> = [
  { key: "fetch_interval_hours", value: "3" },
  { key: "news_feed_limit", value: "100" },
  { key: "retention_days", value: "7" }
];

const upsert = db.prepare(
  "INSERT INTO settings (key, value, updated_at) VALUES (?, ?, unixepoch()) " +
  "ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at"
);

for (const { key, value } of settings) {
  upsert.run(key, value);
  console.log("  upserted: " + key + " = " + value);
}

db.close();
console.log("Settings seed complete.");
