// AUTO-GENERATED by scripts/export-seeds.ts — do not edit by hand
import Database from "better-sqlite3";
import { drizzle } from "drizzle-orm/better-sqlite3";
import { feedSources, newsItems } from "./schema";
import { eq } from "drizzle-orm";
import path from "path";

const sqlite = new Database(path.join(process.cwd(), "db", "command-center.db"));
const db = drizzle(sqlite);

// No stale URLs in this export — the DB is already clean.
const staleUrls: string[] = [];

for (const url of staleUrls) {
  const source = db.select().from(feedSources).where(eq(feedSources.url, url)).get();
  if (source) {
    db.delete(newsItems).where(eq(newsItems.feedSourceId, source.id)).run();
    db.delete(feedSources).where(eq(feedSources.id, source.id)).run();
    console.log("Removed stale feed: " + source.name);
  }
}

const seeds: Array<{
  name: string;
  url: string;
  type: "rss" | "api";
  adapter?: string;
  topicTags: string;
  active: boolean;
}> = [
  {
    name: "Kitware Blog",
    url: "https://www.kitware.com/feed/",
    type: "rss" as "rss" | "api",
    topicTags: "visualization,vtk,paraview",
    active: true,
  },
  {
    name: "Hacker News",
    url: "https://hn.algolia.com/api/v1/search?tags=front_page&hitsPerPage=30",
    type: "api" as "rss" | "api",
    adapter: "hn-algolia",
    topicTags: "tech",
    active: true,
  },
  {
    name: "r/CFD",
    url: "https://www.reddit.com/r/CFD/hot.json?limit=25",
    type: "api" as "rss" | "api",
    adapter: "reddit",
    topicTags: "cfd,fluid-dynamics",
    active: true,
  },
  {
    name: "r/programming",
    url: "https://www.reddit.com/r/programming/hot.json?limit=25",
    type: "api" as "rss" | "api",
    adapter: "reddit",
    topicTags: "programming,tech",
    active: true,
  },
  {
    name: "DEV.to",
    url: "https://dev.to/api/articles?top=7&per_page=20",
    type: "api" as "rss" | "api",
    adapter: "devto",
    topicTags: "dev,programming",
    active: true,
  },
  {
    name: "Lobsters",
    url: "https://lobste.rs/hottest.json",
    type: "api" as "rss" | "api",
    adapter: "lobsters",
    topicTags: "tech,programming",
    active: true,
  },
  {
    name: "Chelsea FC — BBC Sport",
    url: "https://feeds.bbci.co.uk/sport/football/teams/chelsea/rss.xml",
    type: "rss" as "rss" | "api",
    topicTags: "chelsea",
    active: true,
  },
  {
    name: "r/chelseafc",
    url: "https://www.reddit.com/r/chelseafc.json",
    type: "api" as "rss" | "api",
    adapter: "reddit",
    topicTags: "chelsea",
    active: true,
  },
  {
    name: "Chelsea FC YouTube",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCdN2g8KBhCMFXPRgTXz-4sQ",
    type: "rss" as "rss" | "api",
    topicTags: "chelsea,highlights",
    active: true,
  },
  {
    name: "England Football — BBC Sport",
    url: "https://feeds.bbci.co.uk/sport/football/teams/england/rss.xml",
    type: "rss" as "rss" | "api",
    topicTags: "england",
    active: true,
  },
  {
    name: "r/ussoccer",
    url: "https://www.reddit.com/r/ussoccer.json",
    type: "api" as "rss" | "api",
    adapter: "reddit",
    topicTags: "usa",
    active: true,
  }
];

for (const seed of seeds) {
  const existing = db.select().from(feedSources).where(eq(feedSources.url, seed.url)).all();
  if (existing.length === 0) {
    db.insert(feedSources).values(seed).run();
    console.log("Seeded: " + seed.name);
  } else {
    db.update(feedSources).set({
      name: seed.name,
      type: seed.type,
      adapter: seed.adapter ?? null,
      topicTags: seed.topicTags,
      active: seed.active,
    }).where(eq(feedSources.url, seed.url)).run();
    console.log("Updated: " + seed.name);
  }
}

sqlite.close();
console.log("Seed complete.");
