// AUTO-GENERATED by scripts/export-seeds.ts — do not edit by hand
import Database from "better-sqlite3";
import { drizzle } from "drizzle-orm/better-sqlite3";
import { projects, projectItems } from "./schema";
import { eq, and } from "drizzle-orm";
import path from "path";

const sqlite = new Database(path.join(process.cwd(), "db", "command-center.db"));
const db = drizzle(sqlite);

const projectDefs: Array<{
  name: string;
  description: string | null;
  items: Array<{
    title: string;
    notes: string | null;
    status: "idea" | "todo" | "done";
    tags: string | null;
    sortOrder: number;
  }>;
}> = [
  {
    name: "Command Center",
    description: "Personal command center — news feed, memories, and project tracking.",
    items: [
    {
      title: "Projects landing page with project cards",
      notes: "Shows all projects with idea/todo/done counts. Click to navigate into a project.",
      status: "done" as "idea" | "todo" | "done",
      tags: "ui,frontend",
      sortOrder: 0,
    },
    {
      title: "Schema: chelsea_matches table",
      notes: null,
      status: "done" as "idea" | "todo" | "done",
      tags: "chelsea",
      sortOrder: 0,
    },
    {
      title: "Migration: 0009 chelsea_matches",
      notes: null,
      status: "done" as "idea" | "todo" | "done",
      tags: "chelsea",
      sortOrder: 0,
    },
    {
      title: "API: /api/chelsea/matches CRUD",
      notes: null,
      status: "done" as "idea" | "todo" | "done",
      tags: "chelsea",
      sortOrder: 0,
    },
    {
      title: "API: /api/chelsea/sync fixture trigger",
      notes: null,
      status: "done" as "idea" | "todo" | "done",
      tags: "chelsea",
      sortOrder: 0,
    },
    {
      title: "lib/football-fetcher.ts (football-data.org v4)",
      notes: null,
      status: "done" as "idea" | "todo" | "done",
      tags: "chelsea",
      sortOrder: 0,
    },
    {
      title: "Chelsea FC page + ChelseaLanding tabbed component",
      notes: null,
      status: "done" as "idea" | "todo" | "done",
      tags: "chelsea",
      sortOrder: 0,
    },
    {
      title: "ChelseaSchedule component with sync + add",
      notes: null,
      status: "done" as "idea" | "todo" | "done",
      tags: "chelsea",
      sortOrder: 0,
    },
    {
      title: "Seed 5 Chelsea/International feed sources",
      notes: null,
      status: "done" as "idea" | "todo" | "done",
      tags: "chelsea",
      sortOrder: 0,
    },
    {
      title: "Set football_api_key in Settings to enable fixture sync",
      notes: null,
      status: "todo" as "idea" | "todo" | "done",
      tags: "chelsea",
      sortOrder: 0,
    },
    {
      title: "Trigger feed refresh to populate Chelsea news",
      notes: null,
      status: "todo" as "idea" | "todo" | "done",
      tags: "chelsea",
      sortOrder: 0,
    },
    {
      title: "Chelsea FC: Add player stats or transfer tracker tab",
      notes: null,
      status: "idea" as "idea" | "todo" | "done",
      tags: "chelsea",
      sortOrder: 0,
    },
    {
      title: "Chelsea FC: Match day notification via webhook",
      notes: null,
      status: "idea" as "idea" | "todo" | "done",
      tags: "chelsea",
      sortOrder: 0,
    },
    {
      title: "Create / archive / delete projects",
      notes: "New project form on landing page. Archive (soft-hide) or hard-delete with cascade. Archived projects shown in separate toggle.",
      status: "done" as "idea" | "todo" | "done",
      tags: "ui,backend",
      sortOrder: 1,
    },
    {
      title: "Dockerfile + docker-compose.yml",
      notes: "Multi-stage Docker build. SQLite DB mounted as a volume at /app/db so data persists across container restarts.",
      status: "done" as "idea" | "todo" | "done",
      tags: null,
      sortOrder: 2,
    },
    {
      title: "Per-project URL routing (/projects/[id])",
      notes: "Each project has its own URL. Back-arrow returns to landing page.",
      status: "done" as "idea" | "todo" | "done",
      tags: "frontend,routing",
      sortOrder: 2,
    },
    {
      title: "Project rename inline on board",
      notes: "Click the project title on the board to edit it in-place and save via PATCH.",
      status: "todo" as "idea" | "todo" | "done",
      tags: "ui",
      sortOrder: 3,
    },
    {
      title: "Sort projects by last activity",
      notes: "Landing page currently sorts by created date. Sort by most recently updated item would be more useful.",
      status: "todo" as "idea" | "todo" | "done",
      tags: "ui,backend",
      sortOrder: 4,
    },
    {
      title: "Project colour / emoji label",
      notes: "Let users assign a colour or emoji to each project card for quick visual identification.",
      status: "idea" as "idea" | "todo" | "done",
      tags: "ui",
      sortOrder: 5,
    },
    {
      title: "Project-level progress bar",
      notes: "Show done/(todo+done) ratio as a thin progress strip on each landing card.",
      status: "idea" as "idea" | "todo" | "done",
      tags: "ui",
      sortOrder: 6,
    },
    {
      title: "Duplicate project (template)",
      notes: "Copy a project's structure (columns, tags) without its items — useful for repeating workflows.",
      status: "idea" as "idea" | "todo" | "done",
      tags: "feature",
      sortOrder: 7,
    },
    {
      title: "Memories module",
      notes: "Capture UI, tagging, search. Core concept from original plan.",
      status: "idea" as "idea" | "todo" | "done",
      tags: "module,ui,backend",
      sortOrder: 9,
    },
    {
      title: "Docker end-to-end verification",
      notes: "Confirm docker compose up --build works clean on fresh machine.",
      status: "todo" as "idea" | "todo" | "done",
      tags: "devops",
      sortOrder: 10,
    },
    {
      title: "Claude API integration",
      notes: "Auto-capture memories from Claude conversations via API hooks.",
      status: "idea" as "idea" | "todo" | "done",
      tags: "module,ai,api",
      sortOrder: 12,
    },
    {
      title: "Keyword filtering",
      notes: "Filter news feed by keyword/topic across all sources.",
      status: "idea" as "idea" | "todo" | "done",
      tags: "news-feed,ui",
      sortOrder: 13,
    },
    {
      title: "Calendar module",
      notes: "Integrate with Google Calendar or iCal for schedule visibility.",
      status: "idea" as "idea" | "todo" | "done",
      tags: "module,api",
      sortOrder: 14,
    },
    {
      title: "Full-text search",
      notes: "Search across news items, memories, and project notes.",
      status: "idea" as "idea" | "todo" | "done",
      tags: "backend,ui",
      sortOrder: 15,
    },
    {
      title: "Alert on high-score items",
      notes: "Notify when an article exceeds a score threshold (e.g. HN > 500).",
      status: "idea" as "idea" | "todo" | "done",
      tags: "news-feed,notifications",
      sortOrder: 16,
    },
    {
      title: "Export memories to Markdown",
      notes: "Download all memories as .md files for portability.",
      status: "idea" as "idea" | "todo" | "done",
      tags: "memories,export",
      sortOrder: 17,
    },
    {
      title: "r/FluidMechanics feed",
      notes: "Add as a Reddit source alongside r/CFD.",
      status: "idea" as "idea" | "todo" | "done",
      tags: "news-feed,science",
      sortOrder: 18,
    },
    {
      title: "SimScale blog feed",
      notes: "CFD simulation industry news — simscale.com/blog/feed/",
      status: "idea" as "idea" | "todo" | "done",
      tags: "news-feed,science",
      sortOrder: 19,
    },
    {
      title: "Multi-project support",
      notes: "Extend projects board to support multiple projects with a switcher.",
      status: "done" as "idea" | "todo" | "done",
      tags: "module,projects,ui",
      sortOrder: 20,
    },
    {
      title: "Archived items show at the bottom of column with distinct UI demarcation",
      notes: "When show archived is selected, the archived elements appear at the bottom of the column with some distinction to quickly identify them.\n",
      status: "idea" as "idea" | "todo" | "done",
      tags: "projects,ui",
      sortOrder: 21,
    },
    {
      title: "Remove add item from todo and done columns in Projects",
      notes: "There is no need for adding to the todo or done columns\n",
      status: "idea" as "idea" | "todo" | "done",
      tags: "projects,ui",
      sortOrder: 22,
    },
    {
      title: "Project: enable prioritizing tasks by drag and drop reorder",
      notes: "The ideas column should support prioritizing tasks via drag-drop",
      status: "idea" as "idea" | "todo" | "done",
      tags: "projects,ui",
      sortOrder: 31,
    },
    {
      title: "Toast notifications on save",
      notes: "Currently shows inline icon indicators. A small toast system would be cleaner.",
      status: "todo" as "idea" | "todo" | "done",
      tags: "ui,settings",
      sortOrder: 32,
    },
    {
      title: "Manual feed refresh button with status indicator",
      notes: "Show last-refresh time next to each source in the stats table, with a per-source refresh button.",
      status: "idea" as "idea" | "todo" | "done",
      tags: "ui,feeds,settings",
      sortOrder: 33,
    },
    {
      title: "Refresh news feed after clear/purge without full page reload",
      notes: "After purge, the news feed still shows stale data until the user navigates away.",
      status: "todo" as "idea" | "todo" | "done",
      tags: "ui,frontend,settings",
      sortOrder: 34,
    },
    {
      title: "Export / import settings as JSON",
      notes: "Useful when moving between machines or resetting the DB.",
      status: "idea" as "idea" | "todo" | "done",
      tags: "data,settings",
      sortOrder: 35,
    },
    {
      title: "Per-source retention override",
      notes: "Some sources (HN, Reddit) generate lots of items; keep them for fewer days than RSS feeds.",
      status: "idea" as "idea" | "todo" | "done",
      tags: "feeds,data,settings",
      sortOrder: 36,
    },
    {
      title: "Dark/light theme toggle",
      notes: "App is currently hardcoded dark. Could expose as a settings option.",
      status: "idea" as "idea" | "todo" | "done",
      tags: "ui,settings",
      sortOrder: 37,
    },
    {
      title: "Topic tag filtering for feed sources",
      notes: "feed_sources.topic_tags column exists in schema (comma-separated topics) but has no UI � add tag management to FeedSources panel and use tags to filter the news feed.",
      status: "idea" as "idea" | "todo" | "done",
      tags: "news-feed,ui,backend",
      sortOrder: 39,
    },
    {
      title: "Docs module � schema, API, server pages, client components, sidebar",
      notes: "Full module scaffold: docs table with pinned/tags/project_id/updated_at, GET+POST+PATCH+DELETE API routes, server pages with left-join on projects, DocsLanding (list + search + pin toggle), DocDetail (view/edit + react-markdown render + file upload). react-markdown@10 added as dependency.",
      status: "done" as "idea" | "todo" | "done",
      tags: "docs,module,backend,frontend",
      sortOrder: 40,
    },
    {
      title: "Docs: full-text search through document content (SQLite FTS5)",
      notes: "Client-side filter covers title+tags but not content body. FTS5 virtual table would enable searching within markdown content server-side.",
      status: "idea" as "idea" | "todo" | "done",
      tags: "docs,backend",
      sortOrder: 41,
    },
    {
      title: "Docs: export / download doc as .md file",
      notes: "Add a download button on the detail page that triggers a browser download of the current doc content as a .md file.",
      status: "idea" as "idea" | "todo" | "done",
      tags: "docs,ui",
      sortOrder: 42,
    },
    {
      title: "Docs: syntax highlighting in code blocks",
      notes: "react-markdown renders code blocks as plain text. Add react-syntax-highlighter or rehype-highlight to colour-code fenced code blocks.",
      status: "idea" as "idea" | "todo" | "done",
      tags: "docs,ui",
      sortOrder: 43,
    },
    {
      title: "Docs: link docs from a project board card",
      notes: "Allow attaching a doc to a project item (card) so dev notes/specs are one click away from the task.",
      status: "idea" as "idea" | "todo" | "done",
      tags: "docs,projects,ui",
      sortOrder: 44,
    },
    {
      title: "Research Claude agents � best patterns for Command Center integration",
      notes: "Explore the Claude Agent SDK and multi-agent patterns. Goal: identify high-value ways to use agents in the Command Center (e.g. background research, feed summarization, doc generation, scheduled tasks). Produce a plan doc with concrete integration ideas.",
      status: "todo" as "idea" | "todo" | "done",
      tags: "agents,planning",
      sortOrder: 45,
    },
    {
      title: "Docs: mulit-select + delete",
      notes: "Enable multi-select for deleting",
      status: "idea" as "idea" | "todo" | "done",
      tags: "docs,projects,ux",
      sortOrder: 46,
    }
    ],
  },
  {
    name: "RVATech Data Summit 2026",
    description: "Notes and takeaways from the 2026 RVATech Data Summit.",
    items: [

    ],
  },
  {
    name: "Meal Planning",
    description: "New module: Create an inventory of meals we enjoy and enable searching by ingredients",
    items: [
    {
      title: "Create interface",
      notes: "Landing page should allow adding a new meal",
      status: "idea" as "idea" | "todo" | "done",
      tags: null,
      sortOrder: 0,
    }
    ],
  },
  {
    name: "Football",
    description: "New module: news feed, highlight links, schedule, etc. One stop shop for football/Chelsea fans",
    items: [

    ],
  },
  {
    name: "Security",
    description: "Ongoing security audit, hardening, and monitoring for the Command Center app.",
    items: [
    {
      title: "npm audit fix � resolve non-breaking CVEs",
      notes: null,
      status: "done" as "idea" | "todo" | "done",
      tags: "dependencies",
      sortOrder: 0,
    },
    {
      title: "SSRF guard: validate feed URLs against private IP ranges",
      notes: null,
      status: "done" as "idea" | "todo" | "done",
      tags: "api,ssrf",
      sortOrder: 1,
    },
    {
      title: "DOMPurify on Mermaid SVG output (XSS fix)",
      notes: null,
      status: "done" as "idea" | "todo" | "done",
      tags: "xss,rendering",
      sortOrder: 2,
    },
    {
      title: "middleware.ts � localhost-origin guard on all API routes",
      notes: null,
      status: "done" as "idea" | "todo" | "done",
      tags: "auth,api",
      sortOrder: 3,
    },
    {
      title: "CSP + security headers in next.config.ts",
      notes: null,
      status: "done" as "idea" | "todo" | "done",
      tags: "headers",
      sortOrder: 4,
    },
    {
      title: "parseId() helper � NaN-safe ID validation across all routes",
      notes: null,
      status: "done" as "idea" | "todo" | "done",
      tags: "api,validation",
      sortOrder: 5,
    },
    {
      title: "safeHref() � block javascript: URIs in news feed links",
      notes: null,
      status: "done" as "idea" | "todo" | "done",
      tags: "xss,client",
      sortOrder: 6,
    },
    {
      title: "5 MB body size limit on Docs API POST/PATCH",
      notes: null,
      status: "done" as "idea" | "todo" | "done",
      tags: "api,dos",
      sortOrder: 7,
    },
    {
      title: "Protect /api/startup-revalidate with REVALIDATE_SECRET + timingSafeEqual",
      notes: null,
      status: "done" as "idea" | "todo" | "done",
      tags: "api,auth",
      sortOrder: 8,
    },
    {
      title: "Dockerfile: run as non-root nextjs user (uid 1001)",
      notes: null,
      status: "done" as "idea" | "todo" | "done",
      tags: "docker",
      sortOrder: 9,
    },
    {
      title: "safeDocsPath() � path-containment guard on all fs operations",
      notes: null,
      status: "done" as "idea" | "todo" | "done",
      tags: "filesystem",
      sortOrder: 10,
    },
    {
      title: "Log file-write failures in lib/doc-files.ts",
      notes: null,
      status: "done" as "idea" | "todo" | "done",
      tags: "observability",
      sortOrder: 11,
    },
    {
      title: "Pre-commit hook: block commits with high/critical npm CVEs",
      notes: null,
      status: "done" as "idea" | "todo" | "done",
      tags: "ci,dependencies",
      sortOrder: 12,
    },
    {
      title: "eslint-plugin-security � enabled in eslint.config.mjs",
      notes: null,
      status: "done" as "idea" | "todo" | "done",
      tags: "linting",
      sortOrder: 13,
    },
    {
      title: "Security checklist added to CLAUDE.md and enforced in /new-module",
      notes: null,
      status: "done" as "idea" | "todo" | "done",
      tags: "process",
      sortOrder: 14,
    },
    {
      title: "Add REVALIDATE_SECRET to .env.local and docker-compose.yml env section",
      notes: "Set a strong random value (e.g. openssl rand -hex 32). Add to docker-compose.yml as REVALIDATE_SECRET env var so the entrypoint can pass it.",
      status: "done" as "idea" | "todo" | "done",
      tags: "config,auth",
      sortOrder: 15,
    },
    {
      title: "Evaluate mermaid downgrade to v10 to eliminate lodash-es CVEs",
      notes: "mermaid >=11 depends on lodash-es with prototype-pollution CVEs. Downgrade to mermaid@10.9.5 eliminates them but may break diagram syntax. Test with existing docs before committing.",
      status: "todo" as "idea" | "todo" | "done",
      tags: "dependencies",
      sortOrder: 16,
    },
    {
      title: "Add rate limiting to /api/feeds/refresh and /api/settings/purge",
      notes: "These destructive endpoints have no throttle. A simple in-memory token bucket (or next-rate-limit) would prevent abuse if the app is ever network-accessible.",
      status: "todo" as "idea" | "todo" | "done",
      tags: "api,dos",
      sortOrder: 17,
    },
    {
      title: "Run /smoke-check after security changes to verify app health",
      notes: null,
      status: "todo" as "idea" | "todo" | "done",
      tags: "testing",
      sortOrder: 18,
    },
    {
      title: "Full auth system (session or API key) if app is hosted publicly",
      notes: "Current middleware.ts is localhost-only. If self-hosting externally, add a proper auth layer: HTTP Basic behind nginx, or a lightweight session with a single hardcoded password in .env.local.",
      status: "idea" as "idea" | "todo" | "done",
      tags: "auth",
      sortOrder: 19,
    },
    {
      title: "Encrypt SQLite DB at rest (SQLCipher)",
      notes: "better-sqlite3 does not ship SQLCipher by default; would require a custom build. Worthwhile if the machine is shared or the DB contains sensitive data.",
      status: "idea" as "idea" | "todo" | "done",
      tags: "database",
      sortOrder: 20,
    },
    {
      title: "HTTPS / TLS termination in docker-compose.yml",
      notes: "Add an nginx reverse-proxy with a self-signed cert (or Caddy with automatic HTTPS) in front of the Next.js container.",
      status: "idea" as "idea" | "todo" | "done",
      tags: "docker,tls",
      sortOrder: 21,
    },
    {
      title: "Dependabot or Renovate for automated dependency PRs",
      notes: "Add .github/dependabot.yml to auto-open PRs for npm updates. The pre-commit audit gate catches issues at commit time; Dependabot catches them proactively.",
      status: "idea" as "idea" | "todo" | "done",
      tags: "dependencies,ci",
      sortOrder: 22,
    },
    {
      title: "Tighten CSP: remove unsafe-eval once Mermaid supports a nonce/hash",
      notes: "Mermaid v11 currently requires unsafe-eval for its parser. Watch mermaid releases for CSP nonce support, then remove unsafe-eval from next.config.ts.",
      status: "idea" as "idea" | "todo" | "done",
      tags: "headers",
      sortOrder: 23,
    }
    ],
  }
];

for (const def of projectDefs) {
  let project = db.select().from(projects).where(eq(projects.name, def.name)).get();
  if (!project) {
    project = db
      .insert(projects)
      .values({ name: def.name, description: def.description })
      .returning()
      .get();
    console.log("Created project: " + def.name);
  } else {
    console.log("Project exists: " + def.name);
  }

  const pid = project.id;
  const existing = db.select().from(projectItems).where(eq(projectItems.projectId, pid)).all();
  const existingTitles = new Set(existing.map((i) => i.title));

  for (const item of def.items) {
    if (existingTitles.has(item.title)) {
      db.update(projectItems)
        .set({
          notes: item.notes,
          tags: item.tags,
          status: item.status,
          sortOrder: item.sortOrder,
        })
        .where(and(eq(projectItems.projectId, pid), eq(projectItems.title, item.title)))
        .run();
      console.log("  Updated: " + item.title);
    } else {
      db.insert(projectItems)
        .values({
          projectId: pid,
          title: item.title,
          notes: item.notes,
          status: item.status,
          tags: item.tags,
          sortOrder: item.sortOrder,
        })
        .run();
      console.log("  Inserted: " + item.title);
    }
  }
}

sqlite.close();
console.log("\nProject seed complete.");
