/**
 * export-seeds.ts
 *
 * Reads the live DB and regenerates all seed files so they stay in sync
 * with actual data. Run this before committing DB changes.
 *
 * Usage: npx tsx scripts/export-seeds.ts
 *   or:  npm run db:export-seeds
 */

import Database from "better-sqlite3";
import fs from "fs";
import path from "path";

const dbPath = path.join(process.cwd(), "db", "command-center.db");
const db = new Database(dbPath, { readonly: true });

// ── Types ────────────────────────────────────────────────────────────────────

type FeedSourceRow = {
  name: string;
  url: string;
  type: string;
  adapter: string | null;
  topic_tags: string | null;
  active: number;
};

type ProjectRow = {
  id: number;
  name: string;
  description: string | null;
};

type ItemRow = {
  title: string;
  notes: string | null;
  status: string;
  tags: string | null;
  sort_order: number;
};

type SettingRow = {
  key: string;
  value: string;
};

// ── Helpers ──────────────────────────────────────────────────────────────────

function s(val: string | null): string {
  return JSON.stringify(val);
}

function writeSeedFile(filePath: string, content: string): void {
  const cwd = path.resolve(process.cwd());
  const resolved = path.resolve(filePath);
  if (!resolved.startsWith(cwd + path.sep) && resolved !== cwd) {
    throw new Error(`Path traversal attempt blocked: ${resolved}`);
  }
  fs.writeFileSync(resolved, content, "utf8");
  const rel = path.relative(cwd, resolved);
  console.log("  Wrote " + rel);
}

// ── 1. db/seed.ts (feed sources) ─────────────────────────────────────────────

const sources = db
  .prepare("SELECT name, url, type, adapter, topic_tags, active FROM feed_sources ORDER BY id")
  .all() as FeedSourceRow[];

const sourcesLiteral = sources
  .map((s_) => {
    const lines = [
      "  {",
      "    name: " + s(s_.name) + ",",
      "    url: " + s(s_.url) + ",",
      '    type: ' + s(s_.type) + ' as "rss" | "api",',
    ];
    if (s_.adapter !== null) {
      lines.push("    adapter: " + s(s_.adapter) + ",");
    }
    lines.push("    topicTags: " + s(s_.topic_tags ?? "") + ",");
    lines.push("    active: " + (s_.active ? "true" : "false") + ",");
    lines.push("  }");
    return lines.join("\n");
  })
  .join(",\n");

const seedTsContent =
  "// AUTO-GENERATED by scripts/export-seeds.ts — do not edit by hand\n" +
  'import Database from "better-sqlite3";\n' +
  'import { drizzle } from "drizzle-orm/better-sqlite3";\n' +
  'import { feedSources, newsItems } from "./schema";\n' +
  'import { eq } from "drizzle-orm";\n' +
  'import path from "path";\n' +
  "\n" +
  'const sqlite = new Database(path.join(process.cwd(), "db", "command-center.db"));\n' +
  "const db = drizzle(sqlite);\n" +
  "\n" +
  "// No stale URLs in this export — the DB is already clean.\n" +
  "const staleUrls: string[] = [];\n" +
  "\n" +
  "for (const url of staleUrls) {\n" +
  "  const source = db.select().from(feedSources).where(eq(feedSources.url, url)).get();\n" +
  "  if (source) {\n" +
  "    db.delete(newsItems).where(eq(newsItems.feedSourceId, source.id)).run();\n" +
  "    db.delete(feedSources).where(eq(feedSources.id, source.id)).run();\n" +
  '    console.log("Removed stale feed: " + source.name);\n' +
  "  }\n" +
  "}\n" +
  "\n" +
  "const seeds: Array<{\n" +
  "  name: string;\n" +
  "  url: string;\n" +
  '  type: "rss" | "api";\n' +
  "  adapter?: string;\n" +
  "  topicTags: string;\n" +
  "  active: boolean;\n" +
  "}> = [\n" +
  sourcesLiteral +
  "\n];\n" +
  "\n" +
  "for (const seed of seeds) {\n" +
  "  const existing = db.select().from(feedSources).where(eq(feedSources.url, seed.url)).all();\n" +
  "  if (existing.length === 0) {\n" +
  "    db.insert(feedSources).values(seed).run();\n" +
  '    console.log("Seeded: " + seed.name);\n' +
  "  } else {\n" +
  "    db.update(feedSources).set({\n" +
  "      name: seed.name,\n" +
  "      type: seed.type,\n" +
  "      adapter: seed.adapter ?? null,\n" +
  "      topicTags: seed.topicTags,\n" +
  "      active: seed.active,\n" +
  "    }).where(eq(feedSources.url, seed.url)).run();\n" +
  '    console.log("Updated: " + seed.name);\n' +
  "  }\n" +
  "}\n" +
  "\n" +
  "sqlite.close();\n" +
  'console.log("Seed complete.");\n';

writeSeedFile(path.join(process.cwd(), "db", "seed.ts"), seedTsContent);

// ── 2. db/seed-projects.ts (all projects + items) ─────────────────────────────

const allProjects = db
  .prepare("SELECT id, name, description FROM projects WHERE archived = 0 ORDER BY id")
  .all() as ProjectRow[];

const projectDefsLiteral = allProjects
  .map((proj) => {
    const items = db
      .prepare(
        "SELECT title, notes, status, tags, sort_order FROM project_items WHERE project_id = ? AND archived = 0 ORDER BY sort_order"
      )
      .all(proj.id) as ItemRow[];

    const itemsLiteral = items
      .map((item) => {
        return (
          "    {\n" +
          "      title: " + s(item.title) + ",\n" +
          "      notes: " + s(item.notes) + ",\n" +
          '      status: ' + s(item.status) + ' as "idea" | "todo" | "done",\n' +
          "      tags: " + s(item.tags) + ",\n" +
          "      sortOrder: " + item.sort_order + ",\n" +
          "    }"
        );
      })
      .join(",\n");

    return (
      "  {\n" +
      "    name: " + s(proj.name) + ",\n" +
      "    description: " + s(proj.description) + ",\n" +
      "    items: [\n" +
      itemsLiteral +
      "\n    ],\n" +
      "  }"
    );
  })
  .join(",\n");

const seedProjectsTsContent =
  "// AUTO-GENERATED by scripts/export-seeds.ts — do not edit by hand\n" +
  'import Database from "better-sqlite3";\n' +
  'import { drizzle } from "drizzle-orm/better-sqlite3";\n' +
  'import { projects, projectItems } from "./schema";\n' +
  'import { eq, and } from "drizzle-orm";\n' +
  'import path from "path";\n' +
  "\n" +
  'const sqlite = new Database(path.join(process.cwd(), "db", "command-center.db"));\n' +
  "const db = drizzle(sqlite);\n" +
  "\n" +
  "const projectDefs: Array<{\n" +
  "  name: string;\n" +
  "  description: string | null;\n" +
  "  items: Array<{\n" +
  "    title: string;\n" +
  "    notes: string | null;\n" +
  '    status: "idea" | "todo" | "done";\n' +
  "    tags: string | null;\n" +
  "    sortOrder: number;\n" +
  "  }>;\n" +
  "}> = [\n" +
  projectDefsLiteral +
  "\n];\n" +
  "\n" +
  "for (const def of projectDefs) {\n" +
  "  let project = db.select().from(projects).where(eq(projects.name, def.name)).get();\n" +
  "  if (!project) {\n" +
  "    project = db\n" +
  "      .insert(projects)\n" +
  "      .values({ name: def.name, description: def.description })\n" +
  "      .returning()\n" +
  "      .get();\n" +
  '    console.log("Created project: " + def.name);\n' +
  "  } else {\n" +
  '    console.log("Project exists: " + def.name);\n' +
  "  }\n" +
  "\n" +
  "  const pid = project.id;\n" +
  "  const existing = db.select().from(projectItems).where(eq(projectItems.projectId, pid)).all();\n" +
  "  const existingTitles = new Set(existing.map((i) => i.title));\n" +
  "\n" +
  "  for (const item of def.items) {\n" +
  "    if (existingTitles.has(item.title)) {\n" +
  "      db.update(projectItems)\n" +
  "        .set({\n" +
  "          notes: item.notes,\n" +
  "          tags: item.tags,\n" +
  "          status: item.status,\n" +
  "          sortOrder: item.sortOrder,\n" +
  "        })\n" +
  "        .where(and(eq(projectItems.projectId, pid), eq(projectItems.title, item.title)))\n" +
  "        .run();\n" +
  '      console.log("  Updated: " + item.title);\n' +
  "    } else {\n" +
  "      db.insert(projectItems)\n" +
  "        .values({\n" +
  "          projectId: pid,\n" +
  "          title: item.title,\n" +
  "          notes: item.notes,\n" +
  "          status: item.status,\n" +
  "          tags: item.tags,\n" +
  "          sortOrder: item.sortOrder,\n" +
  "        })\n" +
  "        .run();\n" +
  '      console.log("  Inserted: " + item.title);\n' +
  "    }\n" +
  "  }\n" +
  "}\n" +
  "\n" +
  "sqlite.close();\n" +
  'console.log("\\nProject seed complete.");\n';

writeSeedFile(path.join(process.cwd(), "db", "seed-projects.ts"), seedProjectsTsContent);

// ── 3. db/seed-settings-project.ts (compat shim) ─────────────────────────────

const shimContent =
  "// Settings project is now included in db/seed-projects.ts\n" +
  '// Run: npm run seed:projects\n' +
  'console.log("Settings project is seeded by db/seed-projects.ts — run: npm run seed:projects");\n';

writeSeedFile(path.join(process.cwd(), "db", "seed-settings-project.ts"), shimContent);

// ── 4. db/seed-settings.ts (settings table) ───────────────────────────────────

const EXCLUDE_KEYS = new Set(["last_fetched_at"]);

const settingRows = db
  .prepare("SELECT key, value FROM settings ORDER BY key")
  .all() as SettingRow[];

const filteredSettings = settingRows.filter((r) => !EXCLUDE_KEYS.has(r.key));

const settingsLiteral = filteredSettings
  .map((r) => "  { key: " + s(r.key) + ", value: " + s(r.value) + " }")
  .join(",\n");

const seedSettingsContent =
  "// AUTO-GENERATED by scripts/export-seeds.ts — do not edit by hand\n" +
  "// last_fetched_at is intentionally excluded — it is runtime state, not configuration.\n" +
  "// Settings here propagate to any machine that runs this seed after a git pull.\n" +
  'import Database from "better-sqlite3";\n' +
  'import path from "path";\n' +
  "\n" +
  'const db = new Database(path.join(process.cwd(), "db", "command-center.db"));\n' +
  "\n" +
  "const settings: Array<{ key: string; value: string }> = [\n" +
  (settingsLiteral || "  // No settings in DB yet — defaults from lib/settings.ts will be used") +
  "\n];\n" +
  "\n" +
  "const upsert = db.prepare(\n" +
  '  "INSERT INTO settings (key, value, updated_at) VALUES (?, ?, unixepoch()) " +\n' +
  '  "ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at"\n' +
  ");\n" +
  "\n" +
  "for (const { key, value } of settings) {\n" +
  "  upsert.run(key, value);\n" +
  '  console.log("  upserted: " + key + " = " + value);\n' +
  "}\n" +
  "\n" +
  "db.close();\n" +
  'console.log("Settings seed complete.");\n';

writeSeedFile(path.join(process.cwd(), "db", "seed-settings.ts"), seedSettingsContent);

// ── Done ─────────────────────────────────────────────────────────────────────

db.close();
console.log("\nAll seed files regenerated.");
